#!/bin/sh
echo "Running cargo fmt"

errors=0

if ! cargo fmt ./... 2>&1; then
	echo "Please fix the go fmt errors."
	errors=1
	
fi


echo "Running cargo check"

if ! cargo check ; then
	echo "Please fix the cargo check errors."
	errors=1
fi

exit $errors